// Generated by ReScript, PLEASE EDIT WITH CARE


var $$File = {};

var partial_arg = Bun.file;

function readFile(param) {
  return partial_arg.file(param);
}

export {
  $$File ,
  readFile ,
}
/* partial_arg Not a pure module */
