// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Bun from "./bindings/Bun.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";

console.log("Hello, World!");

var file = Bun.readFile("../package.json");

console.log(await Curry._1(file.json, undefined));

export {
  file ,
}
/*  Not a pure module */
